// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/foundry-tools/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r FoundryTools) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *FoundryTools) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r Fleet) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *Fleet) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r GoLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *GoLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r PythonLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *PythonLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r RustLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *RustLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r TSLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *TSLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Fleet":
		switch fnName {
		case "CheckAddedLargeFiles":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).CheckAddedLargeFiles(&parent, ctx)
		case "CheckMergeConflict":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).CheckMergeConflict(&parent, ctx)
		case "CheckYaml":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).CheckYaml(&parent, ctx)
		case "DetectSecrets":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).DetectSecrets(&parent, ctx)
		case "OpengrepSast":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).OpengrepSast(&parent, ctx)
		case "SastRulesetLanes":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).SastRulesetLanes(&parent, ctx)
		case "StopJustifications":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).StopJustifications(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "FoundryTools":
		switch fnName {
		case "Catalogue":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Catalogue(&parent, ctx)
		case "Fleet":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Fleet(&parent), nil
		case "Go":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Go(&parent), nil
		case "Lanes":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Lanes(&parent, ctx)
		case "Python":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Python(&parent), nil
		case "Rust":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Rust(&parent), nil
		case "Ts":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Ts(&parent), nil
		case "Verdicts":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var stage string
			if inputArgs["stage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["stage"]), &stage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg stage", err))
				}
			}
			return (*FoundryTools).Verdicts(&parent, ctx, stage)
		case "":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return New(source), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "GoLane":
		switch fnName {
		case "Build":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Build(&parent, ctx)
		case "Gofmt":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Gofmt(&parent, ctx)
		case "Govulncheck":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Govulncheck(&parent, ctx)
		case "Staticcheck":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Staticcheck(&parent, ctx)
		case "TestRace":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).TestRace(&parent, ctx)
		case "Vet":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Vet(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "PythonLane":
		switch fnName {
		case "ForgeTestkitAssertionFree":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).ForgeTestkitAssertionFree(&parent, ctx)
		case "ForgeTestkitFakePlacement":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).ForgeTestkitFakePlacement(&parent, ctx)
		case "ForgeTestkitSchemaBudget":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).ForgeTestkitSchemaBudget(&parent, ctx)
		case "Mypy":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).Mypy(&parent, ctx)
		case "PipAudit":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).PipAudit(&parent, ctx)
		case "Pytest":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).Pytest(&parent, ctx)
		case "RuffCheck":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).RuffCheck(&parent, ctx)
		case "RuffFormat":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).RuffFormat(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "RustLane":
		switch fnName {
		case "CargoAudit":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoAudit(&parent, ctx)
		case "CargoClippy":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoClippy(&parent, ctx)
		case "CargoFmt":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoFmt(&parent, ctx)
		case "CargoTest":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoTest(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "TSLane":
		switch fnName {
		case "BunAudit":
			var parent TSLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*TSLane).BunAudit(&parent, ctx)
		case "BunGate":
			var parent TSLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*TSLane).BunGate(&parent, ctx)
		case "BunGateCommit":
			var parent TSLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*TSLane).BunGateCommit(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
