// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/foundry-tools/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r FoundryTools) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
		Repo   string
		Sha    string
		Origin string
	}
	concrete.Source = r.Source
	concrete.Repo = r.Repo
	concrete.Sha = r.Sha
	concrete.Origin = r.Origin
	return json.Marshal(&concrete)
}

func (r *FoundryTools) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
		Repo   string
		Sha    string
		Origin string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	r.Repo = concrete.Repo
	r.Sha = concrete.Sha
	r.Origin = concrete.Origin
	return nil
}

func (r Bake) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Context    *dagger.Directory
		Dockerfile string
		BuildArgs  []dagger.BuildArg
		Labels     []string
	}
	concrete.Context = r.Context
	concrete.Dockerfile = r.Dockerfile
	concrete.BuildArgs = r.BuildArgs
	concrete.Labels = r.Labels
	return json.Marshal(&concrete)
}

func (r *Bake) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Context    *dagger.Directory
		Dockerfile string
		BuildArgs  []dagger.BuildArg
		Labels     []string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Context = concrete.Context
	r.Dockerfile = concrete.Dockerfile
	r.BuildArgs = concrete.BuildArgs
	r.Labels = concrete.Labels
	return nil
}

func (r StageResult) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Stage     string
		State     int
		Lanes     []string
		Atoms     []AtomResult
		Omitted   []AtomResult
		Unreached []string
		Log       string
	}
	concrete.Stage = r.Stage
	concrete.State = r.State
	concrete.Lanes = r.Lanes
	concrete.Atoms = r.Atoms
	concrete.Omitted = r.Omitted
	concrete.Unreached = r.Unreached
	concrete.Log = r.Log
	return json.Marshal(&concrete)
}

func (r *StageResult) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Stage     string
		State     int
		Lanes     []string
		Atoms     []AtomResult
		Omitted   []AtomResult
		Unreached []string
		Log       string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Stage = concrete.Stage
	r.State = concrete.State
	r.Lanes = concrete.Lanes
	r.Atoms = concrete.Atoms
	r.Omitted = concrete.Omitted
	r.Unreached = concrete.Unreached
	r.Log = concrete.Log
	return nil
}

func (r Compose) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *Compose) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r Dies) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *Dies) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r Fleet) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *Fleet) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r GoLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *GoLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r Image) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source     *dagger.Directory
		Revision   string
		SourceURL  string
		Title      string
		BuildArgs  []dagger.BuildArg
		Dockerfile string
		Created    string
		Base       string
		BaseDigest string
	}
	concrete.Source = r.Source
	concrete.Revision = r.Revision
	concrete.SourceURL = r.SourceURL
	concrete.Title = r.Title
	concrete.BuildArgs = r.BuildArgs
	concrete.Dockerfile = r.Dockerfile
	concrete.Created = r.Created
	concrete.Base = r.Base
	concrete.BaseDigest = r.BaseDigest
	return json.Marshal(&concrete)
}

func (r *Image) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source     *dagger.Directory
		Revision   string
		SourceURL  string
		Title      string
		BuildArgs  []dagger.BuildArg
		Dockerfile string
		Created    string
		Base       string
		BaseDigest string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	r.Revision = concrete.Revision
	r.SourceURL = concrete.SourceURL
	r.Title = concrete.Title
	r.BuildArgs = concrete.BuildArgs
	r.Dockerfile = concrete.Dockerfile
	r.Created = concrete.Created
	r.Base = concrete.Base
	r.BaseDigest = concrete.BaseDigest
	return nil
}

func (r PythonLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *PythonLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r RustLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *RustLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r TSLane) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *TSLane) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r AtomResult) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Atom          string
		Group         string
		State         int
		Result        string
		Reason        string
		Logs          []string
		Truncated     bool
		OriginalBytes int
		Findings      []Finding
	}
	concrete.Atom = r.Atom
	concrete.Group = r.Group
	concrete.State = r.State
	concrete.Result = r.Result
	concrete.Reason = r.Reason
	concrete.Logs = r.Logs
	concrete.Truncated = r.Truncated
	concrete.OriginalBytes = r.OriginalBytes
	concrete.Findings = r.Findings
	return json.Marshal(&concrete)
}

func (r *AtomResult) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Atom          string
		Group         string
		State         int
		Result        string
		Reason        string
		Logs          []string
		Truncated     bool
		OriginalBytes int
		Findings      []Finding
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Atom = concrete.Atom
	r.Group = concrete.Group
	r.State = concrete.State
	r.Result = concrete.Result
	r.Reason = concrete.Reason
	r.Logs = concrete.Logs
	r.Truncated = concrete.Truncated
	r.OriginalBytes = concrete.OriginalBytes
	r.Findings = concrete.Findings
	return nil
}

func (r Finding) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Verdict string
		Subject string
		Cause   string
		Detail  string
		Probe   string
	}
	concrete.Verdict = r.Verdict
	concrete.Subject = r.Subject
	concrete.Cause = r.Cause
	concrete.Detail = r.Detail
	concrete.Probe = r.Probe
	return json.Marshal(&concrete)
}

func (r *Finding) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Verdict string
		Subject string
		Cause   string
		Detail  string
		Probe   string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Verdict = concrete.Verdict
	r.Subject = concrete.Subject
	r.Cause = concrete.Cause
	r.Detail = concrete.Detail
	r.Probe = concrete.Probe
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Bake":
		switch fnName {
		case "Container":
			var parent Bake
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Bake).Container(&parent), nil
		case "Publish":
			var parent Bake
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ref string
			if inputArgs["ref"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ref"]), &ref)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ref", err))
				}
			}
			var registryUser string
			if inputArgs["registryUser"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUser"]), &registryUser)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUser", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			return (*Bake).Publish(&parent, ctx, ref, registryUser, registryPassword)
		case "Tarball":
			var parent Bake
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Bake).Tarball(&parent), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Compose":
		switch fnName {
		case "Config":
			var parent Compose
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Compose).Config(&parent, ctx)
		case "NoTrackedSecrets":
			var parent Compose
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Compose).NoTrackedSecrets(&parent, ctx)
		case "ThirdPartyPins":
			var parent Compose
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Compose).ThirdPartyPins(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Dies":
		switch fnName {
		case "AdmissionDogfood":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).AdmissionDogfood(&parent, ctx)
		case "CanaryVisibility":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).CanaryVisibility(&parent, ctx)
		case "Canonical":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).Canonical(&parent, ctx)
		case "Contracts":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).Contracts(&parent, ctx)
		case "DataKeys":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).DataKeys(&parent, ctx)
		case "Findings":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).Findings(&parent, ctx)
		case "OpaTest":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).OpaTest(&parent, ctx)
		case "Schema":
			var parent Dies
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dies).Schema(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Fleet":
		switch fnName {
		case "CheckAddedLargeFiles":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).CheckAddedLargeFiles(&parent, ctx)
		case "CheckMergeConflict":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).CheckMergeConflict(&parent, ctx)
		case "CheckYaml":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).CheckYaml(&parent, ctx)
		case "Hadolint":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).Hadolint(&parent, ctx)
		case "OpengrepSast":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).OpengrepSast(&parent, ctx)
		case "OrbitDrift":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).OrbitDrift(&parent, ctx)
		case "SastRulesetLanes":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).SastRulesetLanes(&parent, ctx)
		case "StopJustifications":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).StopJustifications(&parent, ctx)
		case "Witness":
			var parent Fleet
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Fleet).Witness(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "FoundryTools":
		switch fnName {
		case "Bake":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var context string
			if inputArgs["context"] != nil {
				err = json.Unmarshal([]byte(inputArgs["context"]), &context)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg context", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			var buildArgs []string
			if inputArgs["buildArgs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildArgs"]), &buildArgs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildArgs", err))
				}
			}
			var labels []string
			if inputArgs["labels"] != nil {
				err = json.Unmarshal([]byte(inputArgs["labels"]), &labels)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg labels", err))
				}
			}
			return (*FoundryTools).Bake(&parent, context, dockerfile, buildArgs, labels)
		case "Build":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var tip bool
			if inputArgs["tip"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tip"]), &tip)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tip", err))
				}
			}
			var spire *dagger.Socket
			if inputArgs["spire"] != nil {
				err = json.Unmarshal([]byte(inputArgs["spire"]), &spire)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg spire", err))
				}
			}
			var registryAuth *dagger.Secret
			if inputArgs["registryAuth"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryAuth"]), &registryAuth)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryAuth", err))
				}
			}
			var cosignKey *dagger.Secret
			if inputArgs["cosignKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["cosignKey"]), &cosignKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg cosignKey", err))
				}
			}
			var cosignPassphrase *dagger.Secret
			if inputArgs["cosignPassphrase"] != nil {
				err = json.Unmarshal([]byte(inputArgs["cosignPassphrase"]), &cosignPassphrase)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg cosignPassphrase", err))
				}
			}
			var indexUrl string
			if inputArgs["indexURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["indexURL"]), &indexUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg indexURL", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var sourceBase string
			if inputArgs["sourceBase"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceBase"]), &sourceBase)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceBase", err))
				}
			}
			var hades string
			if inputArgs["hades"] != nil {
				err = json.Unmarshal([]byte(inputArgs["hades"]), &hades)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg hades", err))
				}
			}
			var hadesId string
			if inputArgs["hadesID"] != nil {
				err = json.Unmarshal([]byte(inputArgs["hadesID"]), &hadesId)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg hadesID", err))
				}
			}
			var force bool
			if inputArgs["force"] != nil {
				err = json.Unmarshal([]byte(inputArgs["force"]), &force)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg force", err))
				}
			}
			var recordToken *dagger.Secret
			if inputArgs["recordToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["recordToken"]), &recordToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg recordToken", err))
				}
			}
			return nil, (*FoundryTools).Build(&parent, ctx, tip, spire, registryAuth, cosignKey, cosignPassphrase, indexUrl, registry, sourceBase, hades, hadesId, force, recordToken)
		case "Bundle":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var opaSigningKey *dagger.Secret
			if inputArgs["opaSigningKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["opaSigningKey"]), &opaSigningKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg opaSigningKey", err))
				}
			}
			var registryToken *dagger.Secret
			if inputArgs["registryToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryToken"]), &registryToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryToken", err))
				}
			}
			var cosignKey *dagger.Secret
			if inputArgs["cosignKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["cosignKey"]), &cosignKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg cosignKey", err))
				}
			}
			var cosignPassphrase *dagger.Secret
			if inputArgs["cosignPassphrase"] != nil {
				err = json.Unmarshal([]byte(inputArgs["cosignPassphrase"]), &cosignPassphrase)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg cosignPassphrase", err))
				}
			}
			var dryRun bool
			if inputArgs["dryRun"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dryRun"]), &dryRun)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dryRun", err))
				}
			}
			return nil, (*FoundryTools).Bundle(&parent, ctx, opaSigningKey, registryToken, cosignKey, cosignPassphrase, dryRun)
		case "Cast":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var spire *dagger.Socket
			if inputArgs["spire"] != nil {
				err = json.Unmarshal([]byte(inputArgs["spire"]), &spire)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg spire", err))
				}
			}
			var registryToken *dagger.Secret
			if inputArgs["registryToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryToken"]), &registryToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryToken", err))
				}
			}
			var doorbellUrl string
			if inputArgs["doorbellURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["doorbellURL"]), &doorbellUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg doorbellURL", err))
				}
			}
			var hades string
			if inputArgs["hades"] != nil {
				err = json.Unmarshal([]byte(inputArgs["hades"]), &hades)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg hades", err))
				}
			}
			var hadesId string
			if inputArgs["hadesID"] != nil {
				err = json.Unmarshal([]byte(inputArgs["hadesID"]), &hadesId)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg hadesID", err))
				}
			}
			var dryRun bool
			if inputArgs["dryRun"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dryRun"]), &dryRun)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dryRun", err))
				}
			}
			return nil, (*FoundryTools).Cast(&parent, ctx, spire, registryToken, doorbellUrl, hades, hadesId, dryRun)
		case "Catalogue":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Catalogue(&parent, ctx)
		case "Check":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Check(&parent, ctx)
		case "Compose":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Compose(&parent), nil
		case "Dies":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Dies(&parent), nil
		case "Fleet":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Fleet(&parent), nil
		case "Gate":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var tree string
			if inputArgs["tree"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tree"]), &tree)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tree", err))
				}
			}
			var pin string
			if inputArgs["pin"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pin"]), &pin)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pin", err))
				}
			}
			var base string
			if inputArgs["base"] != nil {
				err = json.Unmarshal([]byte(inputArgs["base"]), &base)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg base", err))
				}
			}
			var stage string
			if inputArgs["stage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["stage"]), &stage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg stage", err))
				}
			}
			return (*FoundryTools).Gate(&parent, ctx, tree, pin, base, stage)
		case "GateFile":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var tree string
			if inputArgs["tree"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tree"]), &tree)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tree", err))
				}
			}
			var pin string
			if inputArgs["pin"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pin"]), &pin)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pin", err))
				}
			}
			var base string
			if inputArgs["base"] != nil {
				err = json.Unmarshal([]byte(inputArgs["base"]), &base)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg base", err))
				}
			}
			var stage string
			if inputArgs["stage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["stage"]), &stage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg stage", err))
				}
			}
			var recordToken *dagger.Secret
			if inputArgs["recordToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["recordToken"]), &recordToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg recordToken", err))
				}
			}
			return (*FoundryTools).GateFile(&parent, ctx, tree, pin, base, stage, recordToken)
		case "Go":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Go(&parent), nil
		case "Image":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var revision string
			if inputArgs["revision"] != nil {
				err = json.Unmarshal([]byte(inputArgs["revision"]), &revision)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg revision", err))
				}
			}
			var sourceUrl string
			if inputArgs["sourceURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceURL"]), &sourceUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceURL", err))
				}
			}
			var title string
			if inputArgs["title"] != nil {
				err = json.Unmarshal([]byte(inputArgs["title"]), &title)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg title", err))
				}
			}
			var buildArgs []string
			if inputArgs["buildArgs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildArgs"]), &buildArgs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildArgs", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			return (*FoundryTools).Image(&parent, ctx, revision, sourceUrl, title, buildArgs, dockerfile)
		case "Lanes":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Lanes(&parent, ctx)
		case "Publish":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var token *dagger.Secret
			if inputArgs["token"] != nil {
				err = json.Unmarshal([]byte(inputArgs["token"]), &token)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg token", err))
				}
			}
			var publishUrl string
			if inputArgs["publishURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["publishURL"]), &publishUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg publishURL", err))
				}
			}
			var checkUrl string
			if inputArgs["checkURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["checkURL"]), &checkUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg checkURL", err))
				}
			}
			var user string
			if inputArgs["user"] != nil {
				err = json.Unmarshal([]byte(inputArgs["user"]), &user)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg user", err))
				}
			}
			var indexUrl string
			if inputArgs["indexURL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["indexURL"]), &indexUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg indexURL", err))
				}
			}
			var npmToken *dagger.Secret
			if inputArgs["npmToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["npmToken"]), &npmToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg npmToken", err))
				}
			}
			var npmRegistry string
			if inputArgs["npmRegistry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["npmRegistry"]), &npmRegistry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg npmRegistry", err))
				}
			}
			var dryRun bool
			if inputArgs["dryRun"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dryRun"]), &dryRun)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dryRun", err))
				}
			}
			return nil, (*FoundryTools).Publish(&parent, ctx, token, publishUrl, checkUrl, user, indexUrl, npmToken, npmRegistry, dryRun)
		case "Push":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var base string
			if inputArgs["base"] != nil {
				err = json.Unmarshal([]byte(inputArgs["base"]), &base)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg base", err))
				}
			}
			var origin string
			if inputArgs["origin"] != nil {
				err = json.Unmarshal([]byte(inputArgs["origin"]), &origin)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg origin", err))
				}
			}
			return (*FoundryTools).Push(&parent, ctx, base, origin)
		case "Python":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Python(&parent), nil
		case "Release":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Release(&parent, ctx)
		case "Rust":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Rust(&parent), nil
		case "Tree":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Tree(&parent, ctx)
		case "Ts":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*FoundryTools).Ts(&parent), nil
		case "Verdicts":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var stage string
			if inputArgs["stage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["stage"]), &stage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg stage", err))
				}
			}
			var only string
			if inputArgs["only"] != nil {
				err = json.Unmarshal([]byte(inputArgs["only"]), &only)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg only", err))
				}
			}
			var base string
			if inputArgs["base"] != nil {
				err = json.Unmarshal([]byte(inputArgs["base"]), &base)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg base", err))
				}
			}
			return (*FoundryTools).Verdicts(&parent, ctx, stage, only, base)
		case "":
			var parent FoundryTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var repo string
			if inputArgs["repo"] != nil {
				err = json.Unmarshal([]byte(inputArgs["repo"]), &repo)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg repo", err))
				}
			}
			var sha string
			if inputArgs["sha"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sha"]), &sha)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sha", err))
				}
			}
			return New(source, repo, sha)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "GoLane":
		switch fnName {
		case "Build":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Build(&parent, ctx)
		case "Gofmt":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Gofmt(&parent, ctx)
		case "Govulncheck":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Govulncheck(&parent, ctx)
		case "Mutation":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Mutation(&parent, ctx)
		case "Staticcheck":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Staticcheck(&parent, ctx)
		case "TestRace":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).TestRace(&parent, ctx)
		case "Vet":
			var parent GoLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*GoLane).Vet(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Image":
		switch fnName {
		case "Builder":
			var parent Image
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Image).Builder(&parent), nil
		case "Container":
			var parent Image
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Image).Container(&parent), nil
		case "Publish":
			var parent Image
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ref string
			if inputArgs["ref"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ref"]), &ref)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ref", err))
				}
			}
			var registryUser string
			if inputArgs["registryUser"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUser"]), &registryUser)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUser", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			return (*Image).Publish(&parent, ctx, ref, registryUser, registryPassword)
		case "Tarball":
			var parent Image
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Image).Tarball(&parent), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "PythonLane":
		switch fnName {
		case "ForgeTestkitAssertionFree":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).ForgeTestkitAssertionFree(&parent, ctx)
		case "ForgeTestkitFakePlacement":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).ForgeTestkitFakePlacement(&parent, ctx)
		case "ForgeTestkitSchemaBudget":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).ForgeTestkitSchemaBudget(&parent, ctx)
		case "Mutation":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).Mutation(&parent, ctx)
		case "Mypy":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).Mypy(&parent, ctx)
		case "PipAudit":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).PipAudit(&parent, ctx)
		case "Pytest":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).Pytest(&parent, ctx)
		case "RuffCheck":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).RuffCheck(&parent, ctx)
		case "RuffFormat":
			var parent PythonLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*PythonLane).RuffFormat(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "RustLane":
		switch fnName {
		case "CargoAudit":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoAudit(&parent, ctx)
		case "CargoClippy":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoClippy(&parent, ctx)
		case "CargoFmt":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoFmt(&parent, ctx)
		case "CargoTest":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).CargoTest(&parent, ctx)
		case "Mutation":
			var parent RustLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*RustLane).Mutation(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "StageResult":
		switch fnName {
		case "Exit":
			var parent StageResult
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*StageResult).Exit(&parent, ctx)
		case "Record":
			var parent StageResult
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*StageResult).Record(&parent)
		case "RecordFile":
			var parent StageResult
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*StageResult).RecordFile(&parent)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "TSLane":
		switch fnName {
		case "BunAudit":
			var parent TSLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*TSLane).BunAudit(&parent, ctx)
		case "BunGate":
			var parent TSLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*TSLane).BunGate(&parent, ctx)
		case "Mutation":
			var parent TSLane
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*TSLane).Mutation(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
