package checks

import (
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"
)

// GravityGit is where the fleet's fork of gravity lives. It is read without
// credentials, so a lane can `cargo install --git` it as the test's own failure
// message tells a human to.
const GravityGit = "https://git.notusmi.com/foundry/gravity"

// GravityRegen is one generated binding package that asks to be regenerated in
// the lane: the directory its provenance.json sits in, the environment variable
// that turns its regenerate-and-diff test from a skip into a failure, and the
// gravity commit it pins.
type GravityRegen struct {
	Dir string
	Env string
	Rev string
}

var gravityRevRe = regexp.MustCompile(`^[0-9a-f]{40}$`)

// RegenEnv names the variable a package's regen test reads: the package
// directory, upper-cased, with anything that is not a letter or digit made an
// underscore, then _REGEN_REQUIRED. classescore -> CLASSESCORE_REGEN_REQUIRED,
// which is the name stellar-core-go's tests read today.
//
// A package at the repository root has no directory to name it, so its variable
// is the bare REGEN_REQUIRED.
func RegenEnv(dir string) string {
	if dir == "." {
		return "REGEN_REQUIRED"
	}
	base := strings.ToUpper(path.Base(dir))
	b := []byte(base)
	for i, c := range b {
		if (c < 'A' || c > 'Z') && (c < '0' || c > '9') {
			b[i] = '_'
		}
	}
	return string(b) + "_REGEN_REQUIRED"
}

// RegenTestFile is the file name a package carries when it has the
// regenerate-and-diff test.
const RegenTestFile = "regen_test.go"

// GravityRegens reads every provenance.json a tree carries (path -> contents)
// and answers the packages that were generated by gravity AND carry the
// regenerate-and-diff test (regenTests: the paths of the tree's regen_test.go
// files), in path order.
//
// THE OPT-IN IS A FACT ABOUT THE TREE, not a knob and not the record: a package
// opts in by having both halves, a provenance.json whose generator command
// starts with `gravity` ("regenerate me with gravity at this commit") and the
// regen_test.go that does it. MEASURED on stellar-core-go 2026-10-07: 15
// provenance.json files pin gravity at two different commits, and three of the
// packages have the test. Staging gravity for the other twelve would demand one
// binary satisfy two pins and set a variable no test reads, so a package
// without the test is not listed; when it gains one, it joins. Every other
// provenance.json (a TypeScript core's, a vendored tape's) has no gravity
// generator and is not listed either.
//
// A provenance that names gravity but pins no 40-hex commit is an ERROR rather
// than a skip: a package that cannot say which gravity made it cannot be
// regenerated, and passing it over would be the silent skip this exists to end.
// So is a provenance that is not JSON.
func GravityRegens(files map[string]string, regenTests []string) ([]GravityRegen, error) {
	hasTest := map[string]bool{}
	for _, t := range regenTests {
		if path.Base(t) == RegenTestFile {
			hasTest[path.Dir(t)] = true
		}
	}
	paths := make([]string, 0, len(files))
	for p := range files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	var out []GravityRegen
	for _, p := range paths {
		var prov struct {
			Generator struct {
				Command string `json:"command"`
				Commit  string `json:"commit"`
			} `json:"generator"`
		}
		if err := json.Unmarshal([]byte(files[p]), &prov); err != nil {
			return nil, fmt.Errorf("%s is not JSON: %v", p, err)
		}
		fields := strings.Fields(prov.Generator.Command)
		if len(fields) == 0 || fields[0] != "gravity" || !hasTest[path.Dir(p)] {
			continue
		}
		if !gravityRevRe.MatchString(prov.Generator.Commit) {
			return nil, fmt.Errorf("%s names gravity as its generator but pins %q, not a 40-hex commit", p, prov.Generator.Commit)
		}
		dir := path.Dir(p)
		out = append(out, GravityRegen{Dir: dir, Env: RegenEnv(dir), Rev: prov.Generator.Commit})
	}
	return out, nil
}

// GravityRev answers the one gravity commit a set of packages agree on. One
// binary goes on PATH, so two pins in one tree are an error that names both,
// rather than whichever ran last deciding what the other is held to. Empty
// input answers "" and no error.
func GravityRev(rs []GravityRegen) (string, error) {
	rev := ""
	first := ""
	for _, r := range rs {
		switch {
		case rev == "":
			rev, first = r.Rev, r.Dir
		case r.Rev != rev:
			return "", fmt.Errorf("%s pins gravity %s but %s pins %s; the lane stages one binary, so the pins must agree", first, rev, r.Dir, r.Rev)
		}
	}
	return rev, nil
}

// GravityScope is the line the atom prints about what it staged, so a run says
// whether its regen tests could skip.
func GravityScope(rs []GravityRegen, rev string) string {
	if len(rs) == 0 {
		return "regen: no package pairs a gravity-generated provenance.json with a regen_test.go, so no regenerate-and-diff test is required"
	}
	envs := make([]string, len(rs))
	for i, r := range rs {
		envs[i] = r.Env
	}
	return fmt.Sprintf("regen: gravity %s staged on PATH; %s=1 makes a missing generator a failure, not a skip", rev, strings.Join(envs, "=1, "))
}

// GravityPlan is the whole decision for a tree: which packages, which one
// gravity commit, and the scope line. An error is a tree whose provenance
// cannot be honoured, and the atom files it as a finding.
type GravityPlan struct {
	Regens []GravityRegen
	Rev    string
	Scope  string
}

// PlanGravity reads the tree's provenance.json files and regen tests into a
// plan (GravityRegens, GravityRev, GravityScope).
func PlanGravity(files map[string]string, regenTests []string) (GravityPlan, error) {
	regens, err := GravityRegens(files, regenTests)
	if err != nil {
		return GravityPlan{}, err
	}
	rev, err := GravityRev(regens)
	if err != nil {
		return GravityPlan{}, err
	}
	return GravityPlan{Regens: regens, Rev: rev, Scope: GravityScope(regens, rev)}, nil
}
