package checks

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// THE PYTHON MUTATION GATE'S DECISIONS, in Go. They were foundry-stocks'
// ci/lib/mutation/python.sh, whose seven bash phases drove cosmic-ray and
// forge-testkit-mutation; the atom (atoms_python.go pythonMutation) now runs
// git, uv, cosmic-ray and forge-testkit-mutation as plain execs and settles
// here. forge-testkit-mutation stays the scorer — it is the fleet's library,
// not a lane script — and so do its plan, map, partition and merge.
//
// Only what the atom reached was ported: it never set python.sh's full mode,
// test command, fail-under, timeout, worker count, heartbeat, test-selection
// switch, testkit requirement, index or memory ceiling, and a repo has no say
// in any of them (MutationScope). The heartbeat left with the silence watchdog
// it fed.

// The fleet's python mutation settings, as python.sh defaulted them.
const (
	PythonMutationTimeout = 60
	PythonMutationWorkers = 4
	PythonMutationTestkit = "forge-testkit>=1.9.0"
	PythonMutationIndex   = "https://nexus.notusmi.com/repository/pypi-hosted/simple/"
	// PythonMutationMemory is the data ceiling on every test run, in bytes (4G).
	//
	// EVERY TEST RUN HAS A MEMORY CEILING (Rob, 2026-09-14). A mutant can turn
	// a bounded loop into an unbounded one: forge-testkit#1's
	// `while len(raw) < self.dim`, mutated to `!=`, grew one python to 24.5G,
	// and the engine's buildkit memcg OOM-killed it twice, with whatever ran
	// beside it. RLIMIT_DATA bounds each process's heap and private anonymous
	// memory and is inherited by every child, so a runaway dies with
	// MemoryError and scores as a kill; reserved-but-untouched mappings do not
	// count, which is why it is DATA and not AS. The measure runs under the
	// same ceiling, so a suite that cannot fit fails there, loudly.
	PythonMutationMemory = 4 << 30
)

// PythonTestCommand is the command cosmic-ray runs per mutant and the measure
// runs once: pytest under the memory ceiling. prlimit sets the limit and execs
// the command, where python.sh wrapped it in `bash -c 'ulimit -d …'`. The byte
// count is PythonMutationMemory spelled out, so no package-level expression
// sits where coverage cannot see it; a test holds the two equal.
var PythonTestCommand = []string{"prlimit", "--data=4294967296", "python", "-m", "pytest", "-x", "-q", "-p", "no:cacheprovider"}

// PythonWholeDiffSpecs is the pathspec an undeclared pull's scope is taken
// over: every python source outside the tests. A plain exclusion matches from
// the root only — `:!test_*.py` let forge-testkit#1's containers_gate/test_*.py
// in as 51 mutants — so the exclusions are globs that match at any depth.
var PythonWholeDiffSpecs = []string{"*.py", ":(exclude,glob)**/tests/**", ":(exclude,glob)**/test_*.py", ":(exclude,glob)**/*_test.py", ":(exclude,glob)**/conftest.py"}

var generatedMarker = regexp.MustCompile(`^#.*(GENERATED by|Code generated|@generated|DO NOT EDIT|generated by datamodel-codegen)`)

// PythonGenerated reports whether a module is generated: one of its first 15
// lines is a comment carrying a generator's marker.
//
// GENERATED MODULES LEAVE THE SCOPE (foundry/foundry-stocks#8933). What holds
// generated output is its generator's diff-clean test, not a mutant: 897 of
// stellar_core#18's 2482 scoped mutants sat in kafka_topics/_generated/,
// against an 1800s lane.
func PythonGenerated(source string) bool {
	lines := strings.SplitN(source, "\n", 16)
	for _, ln := range lines[:min(len(lines), 15)] {
		if generatedMarker.MatchString(ln) {
			return true
		}
	}
	return false
}

// CosmicRayConfig is the cosmic-ray TOML for the scoped modules, the one
// forge_testkit.mutation.config writes: module-path (a string for one module,
// an array for several), the per-mutant timeout, and the test command.
func CosmicRayConfig(modules []string, testCommand []string, timeout int) string {
	quote := func(s string) string {
		return `"` + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `"`, `\"`) + `"`
	}
	path := quote(modules[0])
	if len(modules) > 1 {
		quoted := make([]string, len(modules))
		for i, m := range modules {
			quoted[i] = quote(m)
		}
		path = "[" + strings.Join(quoted, ", ") + "]"
	}
	return strings.Join([]string{
		"[cosmic-ray]",
		"module-path = " + path,
		fmt.Sprintf("timeout = %d.0", timeout),
		"excluded-modules = []",
		"test-command = " + quote(strings.Join(testCommand, " ")),
		"",
		"[cosmic-ray.distributor]",
		`name = "local"`,
		"",
	}, "\n")
}

// PythonMutantTimeout is the per-mutant timeout for a suite the measure took
// elapsed seconds to run: twice that, never below the fleet's floor. A mutant
// that needs the whole suite runs it beside its sibling workers, and
// cosmic-ray scores a timeout as a KILL.
func PythonMutantTimeout(elapsedSeconds int) int {
	return max(PythonMutationTimeout, 2*elapsedSeconds)
}

// PythonPlan reads forge-testkit-mutation plan's answer: the workers the
// session's pending jobs can use, and how many are pending.
func PythonPlan(out string) (workers, pending int, ok bool) {
	for _, ln := range strings.Split(out, "\n") {
		if v, found := strings.CutPrefix(ln, "workers="); found {
			workers, ok = atoiOK(v)
		}
		if v, found := strings.CutPrefix(ln, "pending="); found {
			pending, _ = atoiOK(v)
		}
	}
	return workers, pending, ok && workers > 0
}

func atoiOK(s string) (int, bool) {
	n, err := strconv.Atoi(strings.TrimSpace(s))
	return n, err == nil
}

// PythonUnmutable reports whether forge-testkit-mutation scope stood the gate
// down: its step output carries unmutable=true, for a diff whose paths matched
// and none of whose added lines is a mutation site — a docstring, a comment, an
// annotation, a reformat.
func PythonUnmutable(stepOutput string) bool {
	for _, ln := range strings.Split(stepOutput, "\n") {
		if strings.TrimSpace(ln) == "unmutable=true" {
			return true
		}
	}
	return false
}

// PythonMeasureFailure is why an unmutated suite that failed in a worker
// measured nothing — a suite that fails unmutated would score every mutant
// killed — or "" when it exited 0.
func PythonMeasureFailure(worker, status int, log string) string {
	if status == 0 {
		return ""
	}
	why := fmt.Sprintf("the unmutated suite exited %d in worker %d, so every mutant would read as killed and nothing was measured: %s",
		status, worker, tail(log, 3))
	if strings.Contains(log, "MemoryError") {
		why = fmt.Sprintf("the unmutated suite ran out of memory under the %dG ceiling in worker %d; this suite needs a higher one. %s",
			PythonMutationMemory>>30, worker, why)
	}
	return "CANNOT RUN - " + why
}

var scoreLine = regexp.MustCompile(`(?i)honest|standing down|score`)

// PythonReportVerdict settles `forge-testkit-mutation report --fail-under 0`:
// its exit, its report on stdout and its judgement on stderr. The report is
// written before the threshold decides, because the run that fails is the one
// whose survivor list you need (#4710), so every answer carries it.
func PythonReportVerdict(status int, stdout, stderr string) (int, string) {
	summary := "### Mutation gate — python (diff), fail-under 0%\n\n```\n" + withNewline(stdout)
	if stderr != "" {
		summary += withNewline(stderr)
	}
	summary += "```\n"
	switch status {
	case 0:
		line := "the honest score meets the 0% floor (or nothing was gated) — see the report"
		if found := firstMatch(stderr+"\n"+stdout, scoreLine); found != "" {
			line = found
		}
		return 0, line + "\n\n" + summary
	case 1:
		if strings.Contains(stderr, "no mutants ran") {
			return 2, "CANNOT RUN - no mutants ran — the scope kept sites and exec produced nothing; a broken gate, not a low score\n\n" + summary
		}
		line := "the honest score is below the 0% floor — see the survivor list below"
		for _, ln := range strings.Split(stderr, "\n") {
			if strings.HasPrefix(ln, "FAIL:") {
				line = ln
				break
			}
		}
		return 1, line + "\n\n" + summary
	}
	return 2, fmt.Sprintf("CANNOT RUN - forge-testkit-mutation report exited %d — the session could not be read\n\n%s", status, summary)
}

// firstMatch is the first non-blank line of s the pattern matches, trimmed and
// cut to 200 characters.
func firstMatch(s string, re *regexp.Regexp) string {
	for _, ln := range strings.Split(s, "\n") {
		if ln = strings.TrimSpace(ln); ln != "" && re.MatchString(ln) {
			r := []rune(ln)
			return string(r[:min(len(r), 200)])
		}
	}
	return ""
}
