package checks

import (
	"strings"
	"testing"
)

func TestPythonTestCommandRunsPytestUnderTheCeiling(t *testing.T) {
	if got := strings.Join(PythonTestCommand, " "); got != "prlimit --data=4294967296 python -m pytest -x -q -p no:cacheprovider" {
		t.Errorf("test command %q", got)
	}
}

func TestPythonGeneratedReadsTheFirstFifteenLines(t *testing.T) {
	for src, want := range map[string]bool{
		"# GENERATED by protoc\n":                         true,
		"#!/usr/bin/env python\n# Code generated by x.\n": true,
		"# @generated\n":                                  true,
		"#   DO NOT EDIT\n":                               true,
		"# generated by datamodel-codegen:\n":             true,
		strings.Repeat("\n", 14) + "# GENERATED by x":     true,  // line 15
		strings.Repeat("\n", 15) + "# GENERATED by x":     false, // line 16
		`"""GENERATED by nobody, in a docstring."""`:      false,
		"x = 1  # DO NOT EDIT\n":                          false,
		"":                                                false,
	} {
		if got := PythonGenerated(src); got != want {
			t.Errorf("PythonGenerated(%q) = %v, want %v", src, got, want)
		}
	}
}

func TestCosmicRayConfigIsTheOneTestkitWrites(t *testing.T) {
	one := CosmicRayConfig([]string{"src/x.py"}, []string{"python", "-m", "pytest"}, 60)
	want := "[cosmic-ray]\nmodule-path = \"src/x.py\"\ntimeout = 60.0\nexcluded-modules = []\ntest-command = \"python -m pytest\"\n\n[cosmic-ray.distributor]\nname = \"local\"\n"
	if one != want {
		t.Errorf("one module:\n%s\nwant:\n%s", one, want)
	}
	several := CosmicRayConfig([]string{"a.py", `we"ird\.py`}, []string{`sh -c "x"`}, 120)
	for _, w := range []string{`module-path = ["a.py", "we\"ird\\.py"]`, "timeout = 120.0", `test-command = "sh -c \"x\""`} {
		if !strings.Contains(several, w) {
			t.Errorf("several lacks %s:\n%s", w, several)
		}
	}
}

func TestPythonMutantTimeoutIsTwiceTheMeasureWithAFloor(t *testing.T) {
	for elapsed, want := range map[int]int{0: 60, 29: 60, 30: 60, 31: 62, 200: 400} {
		if got := PythonMutantTimeout(elapsed); got != want {
			t.Errorf("PythonMutantTimeout(%d) = %d, want %d", elapsed, got, want)
		}
	}
}

func TestPythonPlan(t *testing.T) {
	for _, c := range []struct {
		out              string
		workers, pending int
		ok               bool
	}{
		{"pending=5\nworkers=4\n", 4, 5, true},
		{"workers=1", 1, 0, true},
		{"pending=0\n", 0, 0, false},
		{"workers=0\n", 0, 0, false},
		{"workers=many\npending=x\n", 0, 0, false},
		{" workers=2\n", 0, 0, false},
	} {
		w, p, ok := PythonPlan(c.out)
		if w != c.workers || p != c.pending || ok != c.ok {
			t.Errorf("PythonPlan(%q) = %d, %d, %v; want %d, %d, %v", c.out, w, p, ok, c.workers, c.pending, c.ok)
		}
	}
}

func TestPythonUnmutable(t *testing.T) {
	if !PythonUnmutable("kept=0\n unmutable=true \n") || PythonUnmutable("unmutable=false\n") || PythonUnmutable("") || PythonUnmutable("# unmutable=true") {
		t.Error("PythonUnmutable reads only an unmutable=true line")
	}
}

func TestPythonMeasureFailure(t *testing.T) {
	if got := PythonMeasureFailure(1, 0, "MemoryError"); got != "" {
		t.Errorf("a suite that passed failed nothing: %q", got)
	}
	got := PythonMeasureFailure(2, 1, "a\nb\nc\nd\n1 failed")
	if !strings.HasPrefix(got, "CANNOT RUN - the unmutated suite exited 1 in worker 2, so every mutant would read as killed") ||
		!strings.HasSuffix(got, "c\nd\n1 failed") || strings.Contains(got, "b\n") || strings.Contains(got, "memory") {
		t.Errorf("failure: %q", got)
	}
	got = PythonMeasureFailure(3, 1, "E   MemoryError")
	if !strings.HasPrefix(got, "CANNOT RUN - the unmutated suite ran out of memory under the 4G ceiling in worker 3; this suite needs a higher one. the unmutated suite exited 1 in worker 3") {
		t.Errorf("memory: %q", got)
	}
}

func TestPythonReportVerdict(t *testing.T) {
	long := strings.Repeat("é", 250)
	for _, c := range []struct {
		name           string
		status         int
		stdout, stderr string
		state          int
		want           []string
		absent         []string
	}{
		{"clean, the score line", 0, "src/x.py: 4 killed\n", "  honest score: 100.0% (4 real kills)\n", 0,
			[]string{"honest score: 100.0% (4 real kills)\n\n### Mutation gate — python (diff), fail-under 0%\n\n```\nsrc/x.py: 4 killed\n  honest score: 100.0% (4 real kills)\n```\n"}, nil},
		{"the score line from the report when stderr has none", 0, "Standing down: nothing scoped", "", 0,
			[]string{"Standing down: nothing scoped\n\n"}, []string{"floor (or nothing"}},
		{"a long score line is cut at 200", 0, "score " + long, "", 0,
			[]string{"score " + strings.Repeat("é", 194) + "\n\n"}, []string{strings.Repeat("é", 195) + "\n\n"}},
		{"no score line", 0, "4 killed", "", 0, []string{"the honest score meets the 0% floor (or nothing was gated) — see the report"}, nil},
		{"survivors", 1, "src/x.py:3 survived", "note\nFAIL: honest 50.0% below 80%\nFAIL: second\n", 1,
			[]string{"FAIL: honest 50.0% below 80%\n\n", "src/x.py:3 survived"}, []string{"FAIL: second\n\n"}},
		{"survivors with no FAIL line", 1, "x", "  FAIL: indented\n", 1, []string{"the honest score is below the 0% floor — see the survivor list below"}, nil},
		{"no mutants ran", 1, "", "no mutants ran\n", 2, []string{"CANNOT RUN - no mutants ran — the scope kept sites"}, nil},
		{"an unreadable session", 2, "", "sqlite3.DatabaseError", 2,
			[]string{"CANNOT RUN - forge-testkit-mutation report exited 2 — the session could not be read", "sqlite3.DatabaseError\n```"}, nil},
		{"no stderr adds no blank line", 3, "report", "", 2, []string{"```\nreport\n```\n"}, nil},
	} {
		state, reason := PythonReportVerdict(c.status, c.stdout, c.stderr)
		if state != c.state {
			t.Errorf("%s: state %d, want %d\n%s", c.name, state, c.state, reason)
		}
		for _, w := range c.want {
			if !strings.Contains(reason, w) {
				t.Errorf("%s: reason lacks %q:\n%s", c.name, w, reason)
			}
		}
		for _, a := range c.absent {
			if strings.Contains(reason, a) {
				t.Errorf("%s: reason carries %q:\n%s", c.name, a, reason)
			}
		}
	}
}
